services:
  db:
    image: ankane/pgvector
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=justin
      - POSTGRES_DB=my-ai=api

volumes:
  db:
