# fly.toml app configuration file generated for my-ai-api on 2023-10-22T08:25:24-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-ai-api"
primary_region = "ord"

[deploy]
  release_command = "npx prisma migrate deploy"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
  grace_period = "25s"
  interval = "10s"
  method = "GET"
  timeout = "5s"
  path = "/public/health-check"
